export const MODELS = [
  {
    partNumber: "MQ0T3AA/A",
    dimensionSteporder: 370,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ0T3",
    imageKey: "iphone-14-pro-spaceblack-select",
    fullPrice: "mq0t3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "256gb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "spaceblack",
  },
  {
    partNumber: "MQ293AA/A",
    dimensionSteporder: 380,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ293",
    imageKey: "iphone-14-pro-deeppurple-select",
    fullPrice: "mq293aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "512gb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "deeppurple",
  },
  {
    partNumber: "MQ2N3AA/A",
    dimensionSteporder: 440,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ2N3",
    imageKey: "iphone-14-pro-silver-select",
    fullPrice: "mq2n3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "1tb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "silver",
  },
  {
    partNumber: "MQ323AA/A",
    dimensionSteporder: 420,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ323",
    imageKey: "iphone-14-pro-deeppurple-select",
    fullPrice: "mq323aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "1tb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "deeppurple",
  },
  {
    partNumber: "MQ023AA/A",
    dimensionSteporder: 320,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ023",
    imageKey: "iphone-14-pro-silver-select",
    fullPrice: "mq023aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "128gb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "silver",
  },
  {
    partNumber: "MQ183AA/A",
    dimensionSteporder: 350,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ183",
    imageKey: "iphone-14-pro-gold-select",
    fullPrice: "mq183aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "256gb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "gold",
  },
  {
    partNumber: "MQ1M3AA/A",
    dimensionSteporder: 410,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ1M3",
    imageKey: "iphone-14-pro-spaceblack-select",
    fullPrice: "mq1m3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "512gb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "spaceblack",
  },
  {
    partNumber: "MQ2V3AA/A",
    dimensionSteporder: 430,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ2V3",
    imageKey: "iphone-14-pro-gold-select",
    fullPrice: "mq2v3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "1tb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "gold",
  },
  {
    partNumber: "MPXV3AA/A",
    dimensionSteporder: 330,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MPXV3",
    imageKey: "iphone-14-pro-spaceblack-select",
    fullPrice: "mpxv3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "128gb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "spaceblack",
  },
  {
    partNumber: "MQ1W3AA/A",
    dimensionSteporder: 400,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ1W3",
    imageKey: "iphone-14-pro-silver-select",
    fullPrice: "mq1w3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "512gb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "silver",
  },
  {
    partNumber: "MQ0G3AA/A",
    dimensionSteporder: 300,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ0G3",
    imageKey: "iphone-14-pro-deeppurple-select",
    fullPrice: "mq0g3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "128gb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "deeppurple",
  },
  {
    partNumber: "MQ1F3AA/A",
    dimensionSteporder: 340,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ1F3",
    imageKey: "iphone-14-pro-deeppurple-select",
    fullPrice: "mq1f3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "256gb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "deeppurple",
  },
  {
    partNumber: "MQ103AA/A",
    dimensionSteporder: 360,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ103",
    imageKey: "iphone-14-pro-silver-select",
    fullPrice: "mq103aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "256gb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "silver",
  },
  {
    partNumber: "MQ233AA/A",
    dimensionSteporder: 390,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ233",
    imageKey: "iphone-14-pro-gold-select",
    fullPrice: "mq233aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "512gb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "gold",
  },
  {
    partNumber: "MQ083AA/A",
    dimensionSteporder: 310,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ083",
    imageKey: "iphone-14-pro-gold-select",
    fullPrice: "mq083aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "128gb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "gold",
  },
  {
    partNumber: "MQ2G3AA/A",
    dimensionSteporder: 450,
    familyType: "iphone14pro",
    productLocatorFamily: "iphone14pro",
    basePartNumber: "MQ2G3",
    imageKey: "iphone-14-pro-spaceblack-select",
    fullPrice: "mq2g3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "1tb",
    dimensionScreensize: "6_1inch",
    dimensionColor: "spaceblack",
  },
  {
    partNumber: "MQAM3AA/A",
    dimensionSteporder: 380,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQAM3",
    imageKey: "iphone-14-pro-max-deeppurple-select",
    fullPrice: "mqam3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "512gb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "deeppurple",
  },
  {
    partNumber: "MQC23AA/A",
    dimensionSteporder: 450,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQC23",
    imageKey: "iphone-14-pro-max-spaceblack-select",
    fullPrice: "mqc23aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "1tb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "spaceblack",
  },
  {
    partNumber: "MQAH3AA/A",
    dimensionSteporder: 400,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQAH3",
    imageKey: "iphone-14-pro-max-silver-select",
    fullPrice: "mqah3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "512gb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "silver",
  },
  {
    partNumber: "MQ9U3AA/A",
    dimensionSteporder: 370,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQ9U3",
    imageKey: "iphone-14-pro-max-spaceblack-select",
    fullPrice: "mq9u3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "256gb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "spaceblack",
  },
  {
    partNumber: "MQ9W3AA/A",
    dimensionSteporder: 350,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQ9W3",
    imageKey: "iphone-14-pro-max-gold-select",
    fullPrice: "mq9w3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "256gb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "gold",
  },
  {
    partNumber: "MQC43AA/A",
    dimensionSteporder: 430,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQC43",
    imageKey: "iphone-14-pro-max-gold-select",
    fullPrice: "mqc43aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "1tb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "gold",
  },
  {
    partNumber: "MQ9X3AA/A",
    dimensionSteporder: 340,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQ9X3",
    imageKey: "iphone-14-pro-max-deeppurple-select",
    fullPrice: "mq9x3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "256gb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "deeppurple",
  },
  {
    partNumber: "MQ9R3AA/A",
    dimensionSteporder: 310,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQ9R3",
    imageKey: "iphone-14-pro-max-gold-select",
    fullPrice: "mq9r3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "128gb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "gold",
  },
  {
    partNumber: "MQ9P3AA/A",
    dimensionSteporder: 330,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQ9P3",
    imageKey: "iphone-14-pro-max-spaceblack-select",
    fullPrice: "mq9p3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "128gb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "spaceblack",
  },
  {
    partNumber: "MQC33AA/A",
    dimensionSteporder: 440,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQC33",
    imageKey: "iphone-14-pro-max-silver-select",
    fullPrice: "mqc33aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "1tb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "silver",
  },
  {
    partNumber: "MQC53AA/A",
    dimensionSteporder: 420,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQC53",
    imageKey: "iphone-14-pro-max-deeppurple-select",
    fullPrice: "mqc53aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "1tb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "deeppurple",
  },
  {
    partNumber: "MQAJ3AA/A",
    dimensionSteporder: 390,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQAJ3",
    imageKey: "iphone-14-pro-max-gold-select",
    fullPrice: "mqaj3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "512gb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "gold",
  },
  {
    partNumber: "MQ9T3AA/A",
    dimensionSteporder: 300,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQ9T3",
    imageKey: "iphone-14-pro-max-deeppurple-select",
    fullPrice: "mq9t3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "128gb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "deeppurple",
  },
  {
    partNumber: "MQAF3AA/A",
    dimensionSteporder: 410,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQAF3",
    imageKey: "iphone-14-pro-max-spaceblack-select",
    fullPrice: "mqaf3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "512gb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "spaceblack",
  },
  {
    partNumber: "MQ9Q3AA/A",
    dimensionSteporder: 320,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQ9Q3",
    imageKey: "iphone-14-pro-max-silver-select",
    fullPrice: "mq9q3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "128gb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "silver",
  },
  {
    partNumber: "MQ9V3AA/A",
    dimensionSteporder: 360,
    familyType: "iphone14promax",
    productLocatorFamily: "iphone14promax",
    basePartNumber: "MQ9V3",
    imageKey: "iphone-14-pro-max-silver-select",
    fullPrice: "mq9v3aa_a",
    seoUrlToken: "",
    displayShippingQuote: null,
    displayPromotion: null,
    carrierPromotionKey: null,
    carrierPolicyType: null,
    carrierPolicyPart: null,
    productMessage: null,
    carrierpromotion: false,
    showShipLabel: false,
    footNotes: null,
    part: "IPHONE14PRO_MAIN",
    threadName: "qtp10523395 ASPEN_primary-15993",
    getReady: false,
    comingSoon: false,
    isPromotionEnabled: false,
    isCarrierDevice: false,
    dimensionCapacity: "256gb",
    dimensionScreensize: "6_7inch",
    dimensionColor: "silver",
  },
];

export const STORES = [
  {
    storeNumber: "R706",
    city: "Abu Dhabi",
    latitude: "24.5",
    storeName: "Al Maryah Island",
    enabled: true,
    longitude: "54.38777777777778",
  },
  {
    storeNumber: "R597",
    city: "Dubai",
    latitude: "25.195613989",
    storeName: "Dubai Mall",
    enabled: true,
    longitude: "55.277543085",
  },
  {
    storeNumber: "R596",
    city: "Dubai",
    latitude: "25.11842",
    storeName: "Mall of the Emirates",
    enabled: true,
    longitude: "55.200543",
  },
  {
    storeNumber: "R595",
    city: "Abu Dhabi",
    latitude: "24.488889",
    storeName: "Yas Mall",
    enabled: true,
    longitude: "54.61",
  },
];
